import 'dart:typed_data';
import 'package:archive/archive.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';

class ZipUploadResult {
  final String downloadUrl;
  final String storagePath;
  final int sizeBytes;
  ZipUploadResult({
    required this.downloadUrl,
    required this.storagePath,
    required this.sizeBytes,
  });
}

class ZipService {
  /// Builds an in-memory ZIP of the generated Flutter project and uploads
  /// it to Firebase Storage at `apps/{uid}/{timestamp}_{appName}.zip`.
  /// Returns a public download URL + storage path.
  static Future<ZipUploadResult?> createAndUploadZip(
      String appName, String dartCode) async {
    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) {
        throw Exception('Not authenticated.');
      }

      // 1. Build ZIP archive
      final archive = Archive();

      final pubspec = '''name: ${appName.toLowerCase().replaceAll(' ', '_')}
description: A new Flutter project generated by TriVerse.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter''';

      archive.addFile(
          ArchiveFile('pubspec.yaml', pubspec.length, pubspec.codeUnits));
      archive.addFile(
          ArchiveFile('lib/main.dart', dartCode.length, dartCode.codeUnits));

      final zipBytes = ZipEncoder().encode(archive);
      if (zipBytes == null) return null;
      final data = Uint8List.fromList(zipBytes);

      // 2. Upload to Firebase Storage
      final safeName = appName.replaceAll(RegExp(r'[^A-Za-z0-9_-]'), '_');
      final filename =
          '${DateTime.now().millisecondsSinceEpoch}_${safeName}.zip';
      final storagePath = 'apps/${user.uid}/$filename';

      final ref = FirebaseStorage.instance.ref().child(storagePath);
      final uploadTask = await ref.putData(
        data,
        SettableMetadata(
          contentType: 'application/zip',
          customMetadata: {
            'appName': appName,
            'userId': user.uid,
          },
        ),
      );

      final downloadUrl = await uploadTask.ref.getDownloadURL();

      return ZipUploadResult(
        downloadUrl: downloadUrl,
        storagePath: storagePath,
        sizeBytes: data.length,
      );
    } catch (e) {
      // ignore: avoid_print
      print('Error uploading ZIP: $e');
      return null;
    }
  }
}
